// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtcV80gv7v1Qs2CF6HcPTZkL1Bv8oghww',
    appId: '1:493078221874:android:7793b96a89d2081117982b',
    messagingSenderId: '493078221874',
    projectId: 'kuppi-buddy',
    storageBucket: 'kuppi-buddy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwPsUgylCS2w8BmN9Mp3rTkxvgfsm83_8',
    appId: '1:493078221874:ios:219678481b9b01d717982b',
    messagingSenderId: '493078221874',
    projectId: 'kuppi-buddy',
    storageBucket: 'kuppi-buddy.appspot.com',
    iosClientId: '493078221874-ektbbsq8aboqeqmhf9a2dg8lsprd3j5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.madhackFinals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwPsUgylCS2w8BmN9Mp3rTkxvgfsm83_8',
    appId: '1:493078221874:ios:219678481b9b01d717982b',
    messagingSenderId: '493078221874',
    projectId: 'kuppi-buddy',
    storageBucket: 'kuppi-buddy.appspot.com',
    iosClientId: '493078221874-ektbbsq8aboqeqmhf9a2dg8lsprd3j5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.madhackFinals',
  );
}
